language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
before_install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          cd "$PYENV_ROOT" && git pull
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
install:
- pip install pytest-cov pytest-mock coveralls flake8 isort gevent==1.1b5 six>=1.10.0 promise>=0.4.2 pytest-benchmark
- pip install pytest==2.9.2
- pip install -e .
script:
- flake8
- py.test --cov=graphql graphql tests
after_success:
- coveralls
matrix:
  include:
    - python: "2.7"
      after_install:
        - pip install cyordereddict
    - python: "3.5"
      after_install:
        - pip install pytest-asyncio
      script:
        - flake8
        - isort --check-only graphql/ -rc
        - py.test --cov=graphql graphql tests tests_py35
